### ISSUE TITLE
User band search story

### ISSUE THREAD

**Issue by ShelbySinz** [DavidsRepos/Project1#4]
## User can type in band name and get venue listing and dates
##Acceptance Criteria 
- [x] working text field and submit button #5
- [x] Return filtered API results #7 #6
- [x] Display results on HTML #23
